server:
  port: 5050

spring:
  application:
    name: refreshable-service

messages:
  welcome: Hello, World 3!

conditional:
  controller:
    enabled: true
    message: Conditional message 6
  service1:
    enabled: true
  service2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'