server:
  port: 5050

spring:
  application:
    name: refreshable-service

messages:
  welcome: Hello, World 3!

conditional:
  controller:
    enabled: true
    message: Conditional message 4

management:
  endpoints:
    web:
      exposure:
        include: '*'