server:
  port: 5050

spring:
  application:
    name: refreshable-service

messages:
  welcome: Hello, World 3!

conditional:
  controller:
    enabled: false
    message: Conditional message 4
  service1:
    enabled: false
  service2:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'